Add prompts to user to create metadata YAML file
SBFRF/SWACSS pull request #13
Opened 2024-12-02 21:50 UTC by kkoetje

User is prompted at end of workflow to create metadata YAML file. Functions that create YAMLs live in their own file mission_yaml_files.py which has been added to the workflow. Mods to yaml structure and wording can be made there.

2024-12-03 00:05 UTC, SBFRF requested changes

2024-12-03 05:06 UTC, kkoetje commented on mission_yaml_files.py
> +
Resolved at beginning of each function.

2024-12-03 19:58 UTC, SBFRF commented
Running through example with Nick d now- comments:
- Default behavior is making a pos file ... I thought we turned that to default look for a pos file
- Ran 20240930 and ran into a timestamp error ... might be associated with making `pos` file
- file mission_summary_metadata.yaml check came up as already existing, questioned overwrite.
- mechanical failure type suggested \n between type
- hitting o (instead of 0) created code to bomb on mechanical failure yaml creation, suggest asking for input again with error regurgitated to user (e.g. didn't recognize that input-try again)
- for mission failure yaml, we keep getting errors requiring an integer, tried 1/0

2024-12-05 03:04 UTC, kkoetje commented
> Running through example with Nick d now- comments:
> 
> * Default behavior is making a pos file ... I thought we turned that to default look for a pos file
> * Ran 20240930 and ran into a timestamp error ... might be associated with making `pos` file
> * file mission_summary_metadata.yaml check came up as already existing, questioned overwrite.
> * mechanical failure type suggested \n between type
> * hitting o (instead of 0) created code to bomb on mechanical failure yaml creation, suggest asking for input again with error regurgitated to user (e.g. didn't recognize that input-try again)
> * for mission failure yaml, we keep getting errors requiring an integer, tried 1/0

2024-12-05 03:06 UTC, kkoetje commented
> > Running through example with Nick d now- comments:
> > 
> > * Default behavior is making a pos file ... I thought we turned that to default look for a pos file
> > * Ran 20240930 and ran into a timestamp error ... might be associated with making `pos` file
> > * file mission_summary_metadata.yaml check came up as already existing, questioned overwrite.
> > * mechanical failure type suggested \n between type
> > * hitting o (instead of 0) created code to bomb on mechanical failure yaml creation, suggest asking for input again with error regurgitated to user (e.g. didn't recognize that input-try again)
> > * for mission failure yaml, we keep getting errors requiring an integer, tried 1/0

All feedback above has been addressed -- significant improvement to error handling have been made, should be much more stable now.

2024-12-05 18:36 UTC, kkoetje commented on mission_yaml_files.py
> +    import yaml
Import statements are now global. Issue created for requirements.txt.

2024-12-05 20:32 UTC, SBFRF commented
Awesome, is this ready for merge?

2024-12-05 21:44 UTC, kkoetje commented
Yes!

2024-12-07 17:44 UTC, SBFRF approved these changes
looks great, thanks @kkoetje

2024-12-07 20:29 UTC, merged